version: "3.9"

services:
    db_sostenibilidad:
        # platform: linux/x86_64 # Comentar si su pc no usa arquitectura ARM
        image: mysql:5.7
        volumes:
            - ./db_data:/var/lib/mysql:rw
        restart: always
        ports:
            - 43307:3306
        environment:
            MYSQL_ROOT_PASSWORD: wordpress
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
        env_file:
            - .env.${APP_ENV}

    wordpress_sostenibilidad:
        depends_on:
            - db_sostenibilidad
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./wp-content:/var/www/sostenibilidad/wp-content/:rw
        ports:
            - "8001:80"
        restart: always
        environment:
            DB_HOST: db_sostenibilidad:3306
            DB_USER: wordpress
            DB_PASSWORD: wordpress
            DB_NAME: wordpress
            USER_S3_ACCESS_KEY_ID: ${USER_S3_ACCESS_KEY_ID}
            USER_S3_ACCESS_KEY_SECRET: ${USER_S3_ACCESS_KEY_SECRET}
        env_file:
            - .env.${APP_ENV}

volumes:
    db_data: {}
    wp-content: {}
